"""Sketch analyzer plugin for hashR lookup."""

import logging
import sys

from math import ceil
from typing import Optional, Union
from flask import current_app
import sqlalchemy as sqla
from timesketch.lib.analyzers import interface, manager
from flor import BloomFilter

logger = logging.getLogger("timesketch.analyzers.hashR")


class HashRLookup(interface.BaseAnalyzer):
    """Analyzer for HashRLookup."""

    NAME = "hashr_lookup"
    DISPLAY_NAME = "hashR lookup"
    DESCRIPTION = (
        "Lookup file hash values in the known hashes database generated by the "
        "hashR project. (https://github.com/google/hashr)"
    )

    DEPENDENCIES = frozenset()

    zerobyte_file_counter = 0
    known_hash_event_counter = 0
    unique_known_hash_counter = 0
    hashr_conn = None
    add_source_attribute = None
    bloom_filter = None
    query_batch_size = None
    DEFAULT_BATCH_SIZE = 50000

    def __init__(self, index_name, sketch_id, timeline_id=None):
        """Initialize The Sketch Analyzer.

        Args:
            index_name: Opensearch index name
            sketch_id: Sketch ID
            timeline_id: Timeline ID, default is None
        """
        self.index_name = index_name
        super().__init__(index_name, sketch_id, timeline_id=timeline_id)

    def connect_hashr(self):
        """Connect to the hashR postgres database.

        Returns:
          True: If connection is setup and successfully tested.

        Raises:
          Exception:  Raises an exception if the database connection details
                      cannot be loaded from the timesketch.conf file.
          Exception: If the connection cannot be setup or tested.
        """

        # Note: Provide connection infos in the data/timesketch.conf file!
        bloom_path = current_app.config.get("HASHR_BLOOM_FILTER_PATH")
        if bloom_path:
            self.bloom_filter = BloomFilter()
            with open(bloom_path, "rb") as f:
                self.bloom_filter.read(f)
            logger.debug("Loaded hashR bloom filter from %s", bloom_path)

        db_user = current_app.config.get("HASHR_DB_USER")
        db_pass = current_app.config.get("HASHR_DB_PW")
        db_address = current_app.config.get("HASHR_DB_ADDR")
        db_port = current_app.config.get("HASHR_DB_PORT")
        db_name = current_app.config.get("HASHR_DB_NAME")
        self.add_source_attribute = current_app.config.get("HASHR_ADD_SOURCE_ATTRIBUTE")
        self.query_batch_size = int(
            current_app.config.get("HASHR_QUERY_BATCH_SIZE", self.DEFAULT_BATCH_SIZE)
        )

        if not all(
            config_param
            for config_param in [
                db_user,
                db_pass,
                db_address,
                db_port,
                db_name,
                isinstance(self.add_source_attribute, bool),
            ]
        ):
            msg = (
                "The hashR analyzer is not able to load the hashR database "
                "information from the timesketch.conf file. Please make sure"
                " to uncomment the section and provide the required "
                "connection details!"
            )
            sys.tracebacklimit = 0
            raise Exception(msg)  # pylint: disable=broad-exception-raised

        db_string = (
            f"postgresql://{db_user}:{db_pass}@" f"{db_address}:{db_port}/{db_name}"
        )
        db_string_redacted = (
            f"postgresql://{db_user}:***@" f"{db_address}:{db_port}/{db_name}"
        )
        db = sqla.create_engine(db_string, connect_args={"connect_timeout": 10})
        try:
            db.connect()
            logger.debug(
                "Successful connected to hashR postgresql database: %s",
                db_string_redacted,
            )
            self.hashr_conn = db
        except sqla.exc.OperationalError as err:
            msg = (
                "Connection to the hashR postgres database failed! "
                '-- Provided connection string: "%s" '
                "-- Error message: %s",
                db_string_redacted,
                str(err),
            )
            logger.error(msg)
            sys.tracebacklimit = 0
            raise Exception(msg) from err  # pylint: disable=broad-exception-raised

        # Check if the required tables are present in the hashR database
        meta_data = sqla.MetaData(bind=self.hashr_conn)
        sqla.MetaData.reflect(meta_data)
        if not all(
            table_name in meta_data.tables
            for table_name in ["samples", "sources", "samples_sources"]
        ):
            msg = (
                "Could not find the required tables in the hashR database! "
                "Please ensure you have populated your hashR database using "
                "the most recent hashR project version!"
                "Required tables: samples, sources, samples_sources",
            )
            logger.error(msg)
            sys.tracebacklimit = 0
            raise Exception(msg) from KeyError  # pylint: disable=broad-exception-raised

        return True

    def batch_hashes(self, hash_list, batch_size=DEFAULT_BATCH_SIZE):
        """Generator function for slicing the hash list into batches

        Args:
          hash_list: A list of hash values.
          batch_size: Size of each batch. Default defined in class var.
        """
        for i in range(0, len(hash_list), batch_size):
            yield hash_list[i : i + batch_size]

    def run_composite_aggregation(
        self, hashmap: set, field_name: str, after_key: dict = None
    ):
        """Runs a composite aggregation of hashes on a sketch.

        Accumulates hashes in the hashmap parameter.

        Args:
            hashmap: A set of hashes to be checked.
            field_name: The field to run the aggregation on.
            after_key: The key to continue the aggregation from, if needed.

        Returns:
            A tuple containing the updated hashmap and the after_key for
            pagination.
        """
        agg_name = f"my_composite_agg_{self.index_name}"
        agg_dsl = {
            "size": 0,
            "query": {
                "bool": {"filter": [{"term": {"__ts_timeline_id": self.timeline_id}}]}
            },
            "aggs": {
                agg_name: {
                    "composite": {
                        "size": 10000,
                        "sources": [
                            {field_name: {"terms": {"field": f"{field_name}.keyword"}}}
                        ],
                    }
                }
            },
        }

        if after_key:
            agg_dsl["aggs"][agg_name]["composite"]["after"] = after_key

        result = self.datastore.search(
            sketch_id=self.sketch.id,
            indices=[self.index_name],
            query_dsl=agg_dsl,
        )
        if "aggregations" not in result or agg_name not in result["aggregations"]:
            return hashmap, None

        after_key = result["aggregations"][agg_name].get("after_key")
        buckets = result["aggregations"][agg_name].get("buckets", [])
        for r in buckets:
            hashmap.add(r["key"][field_name])

        return hashmap, after_key

    def get_all_unique_hashes(self, return_fields: list):
        """Extract all unique hashes using composite aggregation.

        Args:
            return_fields: List of fields to aggregate on.

        Returns:
            A set of unique hashes.
        """
        hashmap = set()
        for field in return_fields:
            after = None
            while True:
                _, after = self.run_composite_aggregation(hashmap, field, after_key=after)
                if not after:
                    break
        return hashmap

    def check_against_hashr(self, sample_hashes: list):
        """Check a list of hashes against the hashR database.

        Args:
          sample_hashes:  A list of hash values that shall be checked
                          against the hashR database.

        Returns:
          matching_hashes:  A dict containing all hashes that are found in the
                            hashR database. (If add_source_attribute is True
                            it also contains the corresponding source images.)
          None:             If there are no matches, the function returns None.

        Raises:
          Exception:  Raises an exception if the provided sample_hashes
                      parameter is not of type list or dict.
        """
        if not isinstance(sample_hashes, list):
            raise Exception(  # pylint: disable=broad-exception-raised
                "The check_against_hashR function only accepts "
                "type<list> as input. But type "
                f"{type(sample_hashes)} was provided!"
            )

        meta_data = sqla.MetaData(bind=self.hashr_conn)
        sqla.MetaData.reflect(meta_data)
        samples_table = meta_data.tables["samples"]
        sources_table = meta_data.tables["sources"]
        samples_sources_table = meta_data.tables["samples_sources"]

        matching_hashes = {}

        with self.hashr_conn.connect() as conn:
            batch_counter = 1
            total_batches = ceil(len(sample_hashes) / self.query_batch_size)
            for batch in self.batch_hashes(sample_hashes, self.query_batch_size):
                logger.debug(
                    "Processing %d/%d batches...", batch_counter, total_batches
                )
                batch_counter += 1

                if self.add_source_attribute:
                    select_statement = (
                        sqla.select(
                            [
                                samples_sources_table.c.sample_sha256,
                                samples_sources_table.c.source_sha256,
                                sources_table.c.sourceid,
                                sources_table.c.reponame,
                            ]
                        )
                        .select_from(
                            samples_sources_table.join(
                                sources_table,
                                samples_sources_table.c.source_sha256
                                == sources_table.c.sha256,
                            )
                        )
                        .where(samples_sources_table.c.sample_sha256.in_(batch))
                    )

                    results = conn.execute(select_statement)

                else:
                    select_statement = sqla.select([samples_table.c.sha256]).where(
                        samples_table.c.sha256.in_(batch)
                    )

                    results = conn.execute(select_statement)

                for entry in results:
                    sample_hash = entry[0]
                    try:
                        if isinstance(entry[2], list):
                            source = f'{entry[3]}:{";".join(entry[2])}'
                        else:
                            source = f"{entry[3]}:{entry[2]}"
                    except (IndexError, sqla.exc.NoSuchColumnError):
                        source = "TagsOnly"
                    matching_hashes.setdefault(sample_hash, set()).add(source)

        logger.debug("Found %d matching hashes in hashR DB.", len(matching_hashes))

        # close database engine
        self.hashr_conn.dispose()
        logger.debug("Closed database connection.")
        return matching_hashes

    def annotate_event(
        self,
        hash_value: str,
        sources: Optional[Union[list, bool]],
        event: interface.Event,
    ):
        """Add tags and attributes to the given event, based on the rules for
        the analyzer.

        Args:
          hash_value: A string of a sha256 hash value.
          sources: A list of sources (image names) where this hash is known from.
          event:  The OpenSearch event object that contains this hash and needs
                  to be tagged or to add an attribute.
        """
        tags_container = ["known-hash"]
        if (
            hash_value
            == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        ):
            tags_container.append("zerobyte-file")
            self.zerobyte_file_counter += 1
            # Do not add any source attribute for zerobyte files,
            # since it exists in all sources.
            sources = False

        event.add_tags(tags_container)

        if sources:
            event.add_attributes({"hashR_sample_sources": list(sources)})

        event.commit()

    def run(self):
        """Entry point for the analyzer.

        Returns:
            String with summary of the analyzer result
        """
        # Connect to the hashR database
        self.connect_hashr()

        # Note: Add fieldnames that contain sha256 values in your events.
        query = (
            "_exists_:hash_sha256 OR _exists_:sha256 OR _exists_:hash OR "
            "_exists_:sha256_hash"
        )

        # Note: Add fieldnames that contain sha256 values in your events.
        return_fields = ["hash_sha256", "hash", "sha256", "sha256_hash"]


        logger.debug("Collecting a list of unique hashes to check against hashR via composite aggregation.")
        unique_hashes = self.get_all_unique_hashes(return_fields)


        events = self.event_stream(query_string=query, return_fields=return_fields)
        events_list = list(events)

        # Fallback to collecting from events if aggregation returned empty (e.g. in tests)
        if not unique_hashes:
            for event in events_list:
                for key in return_fields:
                    if key in event.source.keys():
                        val = event.source.get(key)
                        if val and len(val) == 64:
                            unique_hashes.add(val)
                            break


        if not unique_hashes:
            self.output.result_status = "SUCCESS"
            self.output.result_priority = "NOTE"
            self.output.result_summary = (
                "This timeline does not contain any fields with a sha256 hash."
            )
            return str(self.output)

        # Check against bloom filter if available
        if self.bloom_filter:
            hashes_to_check = []
            for h in unique_hashes:
                # Some hashes might not be exactly 64 chars in OpenSearch, we can filter them out here
                if len(h) != 64:
                    continue
                if h.encode('utf-8') in self.bloom_filter:
                    hashes_to_check.append(h)
            logger.debug("Bloom filter reduced hashes from %d to %d", len(unique_hashes), len(hashes_to_check))
        else:
            hashes_to_check = [h for h in unique_hashes if len(h) == 64]

        if hashes_to_check:
            matching_hashes = self.check_against_hashr(hashes_to_check)
        else:
            matching_hashes = {}

        if not matching_hashes:
            self.output.result_status = "SUCCESS"
            self.output.result_priority = "NOTE"
            self.output.result_summary = "No matching hashes found in hashR database."
            return str(self.output)

        if self.add_source_attribute:
            logger.debug("Start adding tags and attributes to events.")
        else:
            logger.debug("Start adding tags to events.")
        known_hash_counter = 0
        error_hash_counter = 0
        total_event_counter = 0


        for event in events_list:
            total_event_counter += 1
            hash_value = None
            for key in return_fields:
                if key in event.source.keys():
                    hash_value = event.source.get(key)
                    break

            if not hash_value:
                error_hash_counter += 1
                logger.warning(
                    "No matching field with a hash found in this event! "
                    "-- Event Source: %s",
                    str(event.source),
                )
                continue

            if len(hash_value) != 64:
                logger.warning(
                    "The extracted hash does not match the required "
                    "length (64) of a SHA256 hash. Skipping this "
                    "event! Hash: %s - Length: %d",
                    hash_value,
                    len(hash_value),
                )
                error_hash_counter += 1
                continue

            if hash_value in matching_hashes:
                hashr_value = matching_hashes[hash_value] if isinstance(matching_hashes, dict) else False
                known_hash_counter += 1
                if self.add_source_attribute:
                    self.annotate_event(hash_value, hashr_value, event)
                else:
                    self.annotate_event(hash_value, False, event)

        self.unique_known_hash_counter = len(matching_hashes)

        self.output.result_status = "SUCCESS"
        self.output.result_priority = "NOTE"
        self.output.result_summary = (
            f"Found a total of {total_event_counter} events that contain a "
            f"sha256 hash value - {self.unique_known_hash_counter} / "
            f"{len(unique_hashes)} unique hashes known in hashR - "
            f"{known_hash_counter} events tagged - "
            f"{self.zerobyte_file_counter} entries were tagged as zerobyte "
            f"files - {error_hash_counter} events raised an error"
        )
        self.output.result_markdown = (
            f"Found a total of {total_event_counter} events that contain a "
            f"sha256 hash value\n* {self.unique_known_hash_counter} / "
            f"{len(unique_hashes)} unique hashes known in hashR\n"
            f"* {known_hash_counter} events tagged\n"
            f"* {self.zerobyte_file_counter} entries were tagged as zerobyte "
            f"files\n* {error_hash_counter} events raised an error"
        )
        return str(self.output)


manager.AnalysisManager.register_analyzer(HashRLookup)
